Create streak container and GET request
cse110-sp24-group14/cse110-sp24-group14 pull request #73
Opened 2024-06-03 03:48 UTC by tshneour

## Tracking Info

Resolves #47 

## Changes

- Created container for displaying bottom right streaks
- Styled the container to match Figma design
- Created SQL query to select `SiteVisit` dates from database
- Connected streak container to the backend to calculate the current streak
- Separately styled days of the current week which do and do not make up the current streak

## Testing

- Added additional data to `SiteVisits` table then tested through the server

## Confirmation of Change

![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/122496719/27b036ed-69ab-4de7-8a04-4ab4628c88bf)

2024-06-04 17:48 UTC, brentonmdunn commented
Two (hopefully) minor things:
- Fire does not seem to be working as intended. The last day of streak recorded in db is 6/1 so only Sunday should be filled.
- [Modification request] if current date is not in database can you say something along the lines of "Your x day streak broke"?

2024-06-04 18:09 UTC, brentonmdunn requested changes
I added a comment in the conversation section of the PR

2024-06-07 18:53 UTC, brentonmdunn approved these changes

2024-06-07 18:53 UTC, merged

2024-06-07 22:49 UTC, dylantrann commented
From the database, it seems like the streak should only have Friday (6/7/24) ignited but it ignites Thursday as well. Could be a bug?
![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/122491673/1bb717c7-8000-464b-a5d4-d32432260353)

![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/122491673/6ba9ee89-3566-4b9f-961b-6c3432fdb05e)