Post to do and call streaks
cse110-sp24-group14/cse110-sp24-group14 pull request #83
Opened 2024-06-05 05:04 UTC by hritikbharucha

## Tracking Info

Resolves #77 and Resolves #81

## Changes

- Created a SQL query to insert a new task with a title and date into the database
- Called the post streaks function on site load to always update streaks

## Testing

- Used Docker and LiveServer
- Console confirmed streaks were updated on site load and prevented duplicates
- Pop up confirmed task was successfully created

## Confirmation of Change

![Screenshot 2024-06-04 at 9 55 00 PM](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/72780268/6b145b67-4254-406d-b71d-0e3f323897f7)

<img width="487" alt="Screenshot 2024-06-04 at 9 58 03 PM" src="https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/72780268/1ee75aa9-1bef-45c3-aa56-db22a1d9bd80">

2024-06-06 06:58 UTC, OasisAlex commented on source/server.js
> -    port: 3307
Why is this deleted?

2024-06-06 07:47 UTC, OasisAlex requested changes
- Issue when I try to create a server, I think the issue was the missing line of port:3307
![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/114462126/a75d40bb-3421-430f-9280-5a3b5f1ee3fa)
added it in my end, it's working after.
- [x] Try call streaks and view it in database 
![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/114462126/9c3877da-f293-4bf2-80b2-7a825e6df82d)
![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/114462126/85a08178-80b0-4c3a-ad55-5c0a9a3dde0c)
![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/114462126/1e647274-977b-40b8-8447-caf2317b6405)

- [x] POST tasks I used crul in command line 
![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/114462126/fddaa14a-a375-465a-8be4-26582861faee)


![image](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/114462126/8508c14c-2844-49be-b11b-ec0a221dcc73)

2024-06-06 18:13 UTC, hritikbharucha commented on source/server.js
> -    port: 3307
Oh good catch, I must have accidentally deleted at some point.

2024-06-06 23:14 UTC, OasisAlex commented on source/server.js
> -    port: 3307
Oh, okay. Then the rest looks fine

2024-06-06 23:14 UTC, OasisAlex approved these changes

2024-06-06 23:57 UTC, EdwardLinS requested changes
I tested both features and they work well. I changed the date of my computer to see if the streaks updated correctly and it works perfectly. 

Just one small request: in the issue, the task creation call should be called when the user submits through the form. Other than that one change, everything is good! Nice job!

2024-06-07 06:28 UTC, hritikbharucha commented
> Just one small request: in the issue, the task creation call should be called when the user submits through the form. Other than that one change, everything is good! Nice job!

I added a temporary form in index.html that calls the task creation on form submission and confirmed that the tasks were added to the database. 
![Screenshot 2024-06-06 at 11 24 31 PM](https://github.com/cse110-sp24-group14/cse110-sp24-group14/assets/72780268/ee6215b1-b054-4b6e-8c1d-9b7dfbc8db88)

2024-06-07 08:07 UTC, EdwardLinS approved these changes
Thanks for adding the form! I looked through it all and everything works flawlessly. I re-added the port number in server for consistency with the rest of the repo and change it so that new inserted tasks start as incomplete through the starter.sql. 

Great job!

2024-06-07 08:07 UTC, EdwardLinS commented on source/starter.sql
> +    completed BOOLEAN DEFAULT FALSE,
For clarity, I changed this to allow inserted tasks to start as incompleted.

2024-06-07 08:21 UTC, merged